### ISSUE TITLE
deploy failed: Did not specify @options[:s3_bucket] nil (RuntimeError)

### ISSUE THREAD

**Issue by shukrikhalid** [tongueroo/jets#121]
Hi, i try to deploy but failed

jets 1.4.5
ruby 2.5.0

```
. . .
=> Replacing compiled gems with AWS Lambda Linux compiled versions: /tmp/jets/demo_api/stage/opt
Checking projects gems for pre-built Lambda gems...
Gem nokogiri-1.9.1 unpacked at /tmp/jets/demo_api/stage/opt
Gem mysql2-0.5.2 unpacked at /tmp/jets/demo_api/stage/opt
=> Generating shims in the handlers folder.
=> Creating zip file for /tmp/jets/demo_api/stage/opt
=> cd /tmp/jets/demo_api/stage/opt && zip --symlinks -rq opt.zip .
Zip file created at: /tmp/jets/demo_api/stage/zips/opt-db69d82a.zip (16.7 MB)
=> Creating zip file for /tmp/jets/demo_api/stage/code
=> cd /tmp/jets/demo_api/stage/code && zip --symlinks -rq code.zip .
Zip file created at: /tmp/jets/demo_api/stage/zips/code-817683ad.zip (21 KB)
Building CloudFormation templates.
Traceback (most recent call last):
	16: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
	15: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
	14: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/bin/jets:23:in `<main>'
	13: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/bin/jets:23:in `load'
	12: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/exe/jets:14:in `<top (required)>'
	11: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/cli.rb:5:in `start'
	10: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/cli.rb:21:in `start'
	 9: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/commands/base.rb:27:in `perform'
	 8: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/commands/base.rb:38:in `dispatch'
	 7: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 6: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 5: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 4: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/commands/main.rb:21:in `deploy'
	 3: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/commands/deploy.rb:31:in `run'
	 2: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/commands/deploy.rb:67:in `ship'
	 1: from /Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/cfn/ship.rb:14:in `run'
/Users/shukrikhalid/.rvm/gems/ruby-2.5.0/gems/jets-1.4.5/lib/jets/cfn/ship.rb:172:in `upload_to_s3': Did not specify @options[:s3_bucket] nil (RuntimeError)
```
when I run `jets deploy` got error

s3 bucket is created but is empty

**Comment by shukrikhalid** [comment]
sorry, it solve.
i use rvm got issue include (Aws::CloudFormation::Errors::Throttling). 
so try changes to rbenv everything is fine.
