### ISSUE TITLE
Jets Deploy Afterburner Mode Errors for Rails API Mode apps

### ISSUE THREAD

**Issue by tongueroo** [tongueroo/jets#141]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | Amazon Linux AMI 2018.03        |
| Jets             | 1.5.2        |
| Ruby             |  2.5.3       |

---

## Expected Behaviour

Jets Afterburner deploys a Rails application that is in Rails API Mode successfully.

## Current Behavior

The deploy is erroring. 

## Step-by-step reproduction instructions

    git clone https://github.com/tongueroo/demo-rails-api
    mkdir -p .jets/app
    vim .jets/app/.env # add DATABASE_URL
    jets deploy

Stack trace:

```
Bundle complete! 84 Gemfile dependencies, 228 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
=> cd /tmp/jets/turbo-wrapper-project/rack && bundle exec rake assets:clobber --trace
rake aborted!
Don't know how to build task 'assets:clobber' (See the list of available tasks with `rake --tasks`)
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task_manager.rb:59:in `[]'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:159:in `invoke_task'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/josue/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/josue/.rvm/gems/ruby-2.5.3/bin/rake:23:in `load'
/home/josue/.rvm/gems/ruby-2.5.3/bin/rake:23:in `<top (required)>'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/josue/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/home/josue/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `load'
/home/josue/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
cd /tmp/jets/turbo-wrapper-project/rack && bundle exec rake assets:clobber --trace failed to run.
/home/josue/.rvm/gems/ruby-2.5.3/gems/jets-1.5.1/lib/jets/builders/code_builder.rb:231:in `rails_assets'
```

## Code Sample

https://github.com/tongueroo/demo-rails-api

Reference: https://community.rubyonjets.com/t/error-while-deploying-rails-api-mode/47

**Comment by tongueroo** [comment]
Fixed released in v1.5.3 [CHANGELOG](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)
