### ISSUE TITLE
Jets shouldn't fail silently on rsync calls if rsync doesn't exist.

### ISSUE THREAD

**Issue by jorihardman** [tongueroo/jets#174]
Commit https://github.com/tongueroo/jets/commit/1f20a6cc115f265c596a94f5be05c13abc3e8494 replaced some recursive copy functionality with rsync calls. My first attempt at deploying with jets was done from within a debian-based docker container, which doesn't have rsync by default. The rsync command is run with `quite: true` so when it fails, there is no output, and the deploy fails with a cryptic error:

```
Traceback (most recent call last):
        12: from /usr/local/bundle/bin/jets:23:in `<main>'
        11: from /usr/local/bundle/bin/jets:23:in `load'
        10: from /usr/local/bundle/gems/jets-1.6.5/exe/jets:14:in `<top (required)>'
         9: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/cli.rb:5:in `start'
         8: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/cli.rb:20:in `start'
         7: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/cli.rb:48:in `boot_jets'
         6: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/core.rb:18:in `boot'
         5: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/booter.rb:7:in `boot!'
         4: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/booter.rb:31:in `turbo_charge'
         3: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/turbo.rb:15:in `charge'
         2: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/turbo/rail.rb:13:in `setup'
         1: from /usr/local/bundle/gems/jets-1.6.5/lib/jets/turbo/rail.rb:44:in `wrapper_jets_project'
/usr/local/bundle/gems/jets-1.6.5/lib/jets/turbo/rail.rb:44:in `write': No such file or directory @ rb_sysopen - /tmp/jets/turbo-wrapper-project/date.txt (Errno::ENOENT)
```

I think having rsync is a reasonable assumption, but perhaps remove `quiet: true` from https://github.com/tongueroo/jets/blob/95e7d74bbb7d764693287068c6e9e8ba549d3112/lib/jets/util.rb#L16 so the failure is more obvious.

**Comment by tongueroo** [comment]
Handled in #177 Will go out in next release
