### ISSUE TITLE
Jets new fails during jets webpacker:install

### ISSUE THREAD

**Issue by lefthand** [tongueroo/jets#193]
- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |  Amazon Linux       |
| Jets             |   1.8      |
| Ruby             |  2.5.1       |

---

## Expected Behaviour

Using Cloud9, `jets new demo` will setup my project.

## Current Behavior

Setup fails during `jets webpacker:install` execution. `config/webpack/environment.js` doesn't get setup and this error is thrown `/active_support/inflector/methods.rb:285:in `const_get': uninitialized constant Jets::Job::S3EventHelper (NameError)`

## Step-by-step reproduction instructions

* Start a new Cloud9 host
* Install and use Ruby 2.5
  * `rvm install 2.5.1 && rvm use 2.5.1 --default`
* Install jets
  * `gem install jets`
* Install yarn
  * `npm install -g yarn`
* Install mysql client
  * `sudo yum install mysql-devel`
* Start new project
  * `jets new demo`

```
Using webpacker 3.2.0 from https://github.com/tongueroo/webpacker.git (at jets@3651cc3)
Bundle complete! 10 Gemfile dependencies, 76 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  jets webpacker:install from "."
Traceback (most recent call last):
        18: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        17: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        16: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/jets:23:in `<main>'
        15: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/jets:23:in `load'
        14: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/exe/jets:14:in `<top (required)>'
        13: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/cli.rb:5:in `start'
        12: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/cli.rb:20:in `start'
        11: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/cli.rb:48:in `boot_jets'
        10: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/core.rb:18:in `boot'
         9: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/booter.rb:14:in `boot!'
         8: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/booter.rb:153:in `eager_load_jets'
         7: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/booter.rb:153:in `select'
         6: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/booter.rb:165:in `block in eager_load_jets'
         5: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
         4: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/inflector/methods.rb:281:in `constantize'
         3: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/inflector/methods.rb:281:in `inject'
         2: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/inflector/methods.rb:281:in `each'
         1: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/inflector/methods.rb:285:in `block in constantize'
/home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/inflector/methods.rb:285:in `const_get': uninitialized constant Jets::Job::S3EventHelper (NameError)
      insert  config/webpack/environment.js
Traceback (most recent call last):
        24: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        23: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        22: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/jets:23:in `<main>'
        21: from /home/ec2-user/.rvm/gems/ruby-2.5.1/bin/jets:23:in `load'
        20: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/exe/jets:14:in `<top (required)>'
        19: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/cli.rb:5:in `start'
        18: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/cli.rb:21:in `start'
        17: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/commands/base.rb:27:in `perform'
        16: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/commands/base.rb:38:in `dispatch'
        15: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        14: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        13: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        12: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
        11: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        10: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
         9: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
         8: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
         7: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
         6: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
         5: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         4: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         3: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/jets-1.8.0/lib/jets/commands/new.rb:106:in `bootstrap_install'
         2: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/inject_into_file.rb:27:in `insert_into_file'
         1: from /home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions.rb:94:in `action'
/home/ec2-user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/inject_into_file.rb:60:in `invoke!': The file /home/ec2-user/environment/welp/config/webpack/environment.js does not appear to exist (Thor::Error)
```

**Comment by tongueroo** [comment]
Addressed in #194.  Released in [v1.8.1](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)
