### ISSUE TITLE
jets commands fail to run under afterburner mode 

### ISSUE THREAD

**Issue by aoozdemir** [tongueroo/jets#210]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software             | Version |
| ---------------- | -------  |
| Operating System | MacOS High Sierra 10.13.6        |
| Jets                        |    1.8.7     |
| Ruby                       |     2.5.3p105    |
| Rails                       | 5.2.2 |

---

## Expected Behaviour

Using jets afterburner mode, `jets` commands should run successfully in rails folder.

## Current Behavior

When run under rails folder, `jets` commands throw an error with `cannot load such file -- jets-html-sanitizer (LoadError)`

<details><summary>see error logs</summary>

```shell
➜ q_pool git:(master) jets --version
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/version.rb:4: warning: already initialized constant JSON::VERSION
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/version.rb:4: warning: previous definition of VERSION was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/version.rb:5: warning: already initialized constant JSON::VERSION_ARRAY
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/version.rb:5: warning: previous definition of VERSION_ARRAY was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/version.rb:6: warning: already initialized constant JSON::VERSION_MAJOR
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/version.rb:6: warning: previous definition of VERSION_MAJOR was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/version.rb:7: warning: already initialized constant JSON::VERSION_MINOR
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/version.rb:7: warning: previous definition of VERSION_MINOR was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/version.rb:8: warning: already initialized constant JSON::VERSION_BUILD
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/version.rb:8: warning: previous definition of VERSION_BUILD was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:100: warning: already initialized constant JSON::NaN
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:100: warning: previous definition of NaN was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:102: warning: already initialized constant JSON::Infinity
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:102: warning: previous definition of Infinity was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:104: warning: previous definition of MinusInfinity was here
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:129: warning: already initialized constant JSON::UnparserError
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:129: warning: previous definition of UnparserError was here
Traceback (most recent call last):
	65: from /Users/oz/.rbenv/versions/2.5.3/bin/jets:23:in `<main>'
	64: from /Users/oz/.rbenv/versions/2.5.3/bin/jets:23:in `load'
	63: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/exe/jets:14:in `<top (required)>'
	62: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/cli.rb:5:in `start'
	61: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/cli.rb:18:in `start'
	60: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/cli.rb:114:in `lookup'
	59: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/commands/rake_command.rb:23:in `namespaced_commands'
	58: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/commands/rake_command.rb:27:in `formatted_rake_tasks'
	57: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/commands/rake_command.rb:38:in `rake_tasks'
	56: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/commands/rake_tasks.rb:14:in `load!'
	55: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/lib/jets/booter.rb:98:in `require_bundle_gems'
	54: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
	53: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
	52: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
	51: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
	50: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
	49: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	48: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
	47: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ransack-2.1.1/lib/ransack.rb:23:in `<top (required)>'
	46: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	45: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	44: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	43: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	42: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ransack-2.1.1/lib/ransack/helpers.rb:1:in `<top (required)>'
	41: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	40: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	39: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	38: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	37: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ransack-2.1.1/lib/ransack/helpers/form_builder.rb:3:in `<top (required)>'
	36: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	35: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	34: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	33: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	32: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers.rb:5:in `<top (required)>'
	31: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers.rb:6:in `<module:ActionView>'
	30: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers.rb:54:in `<module:Helpers>'
	29: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	28: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	27: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	26: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	25: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/form_helper.rb:6:in `<top (required)>'
	24: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	23: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	22: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	21: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	20: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/form_tag_helper.rb:8:in `<top (required)>'
	19: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/form_tag_helper.rb:10:in `<module:ActionView>'
	18: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/form_tag_helper.rb:16:in `<module:Helpers>'
	17: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/form_tag_helper.rb:20:in `<module:FormTagHelper>'
	16: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	15: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	14: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	13: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	12: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/text_helper.rb:6:in `<top (required)>'
	11: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/text_helper.rb:8:in `<module:ActionView>'
	10: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/text_helper.rb:31:in `<module:Helpers>'
	 9: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/text_helper.rb:34:in `<module:TextHelper>'
	 8: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 7: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 6: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	 5: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 4: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.7/vendor/rails/actionview/lib/action_view/helpers/sanitize_helper.rb:4:in `<top (required)>'
	 3: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 2: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 1: from /Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/oz/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- jets-html-sanitizer (LoadError)
```
</details>

## Step-by-step reproduction instructions

OK! I was following `jets`'s documentation and got pretty excited when I saw how easy it was to deploy a rails app to aws lambda. And it worked. Problem is, I wanted to migrate my production database and see if that's possible or as easy as deploying.

Steps are;
1. run `rails new app_name -T -d postgresql --api`
2. do what you need to do with the rails app
3. run `jets deploy` (to see this works)
4. success
5. run `jets --version` while in the rails folder
6. boom 💥 

## Code Sample

<details><summary>my Gemfile in Rails</summary>

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'rails', '~> 5.2.2'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'rack-cors'
gem 'annotate'
gem 'kaminari'
gem 'ransack'
gem 'jwt'
gem 'httparty'
gem 'discard', '~> 1.0'
gem 'fast_jsonapi', '~> 1.5'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
</details>

## Solution Suggestion

No idea currently, but happy to help if found something.

**Comment by tongueroo** [comment]
@aoozdemir Thanks for the detailed issue report. Looks like within a rails folder `jets --version` doesnt work, but `jets version` does. Dug into it a little bit and figured `jets version` suffices for now 👌

Will consider PRs for `jets --version` to work in a Rails folder though.

**Comment by aoozdemir** [comment]
Thank you @tongueroo. Sorry, I was quite busy last week (still am, unfortunately) with my job. Couldn't get a chance to look deeper into this. However, if I recall correctly, the only problem wasn't the `--version` command, but others as well, e.g. `db:migrate`.

But, to keep it clean issue can stay closed. I'll ping you if I find anything more on this issue.

Bests.

**Comment by tongueroo** [comment]
@aoozdemir All good.  Yup for migrations, recommend using `rails db:migrate` instead. The way afterburner mode works is that only `jets deploy` works. Because we're not really in a jets app, we're in a rails app. So you use all the normal rails commands except for deployment. Hope that helps. 👌

**Comment by aoozdemir** [comment]
@tongueroo aah! That makes sense. I went with the jets command with an impulse. Thanks a lot for the explanation.
