### ISSUE TITLE
NameError: uninitialized constant ActionMailer

### ISSUE THREAD

**Issue by nightswinger** [tongueroo/jets#286]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | OSX 10.13.6|
| Jets             |      1.9.12   |
| Ruby             |    2.5.3     |

---

## Current Behavior

error occurred when running `bundle exec jets console` command.

```
bundler: failed to load command: jets (/Users/NightSwinger/.rbenv/versions/2.5.3/bin/jets)
NameError: uninitialized constant ActionMailer
  /Users/NightSwinger/visionsofblue89/garbages/actionmailer/app/mailers/application_mailer.rb:1:in `<top (required)>'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:16:in `require'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:16:in `require'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/core_ext/kernel.rb:11:in `require'
  /Users/NightSwinger/visionsofblue89/garbages/actionmailer/app/mailers/user_mailer.rb:1:in `<top (required)>'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:16:in `require'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:16:in `require'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/core_ext/kernel.rb:11:in `require'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:369:in `block (2 levels) in eager_load'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:666:in `block in ls'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:663:in `foreach'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:663:in `ls'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:365:in `block in eager_load'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:360:in `synchronize'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/loader.rb:360:in `eager_load'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/stack.rb:77:in `eager_load_shared_resources!'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/stack.rb:70:in `has_resources?'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/application.rb:212:in `default_iam_policy'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/application.rb:188:in `set_iam_policy'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/application.rb:23:in `configs!'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/booter.rb:22:in `boot!'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/core.rb:18:in `boot'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/cli.rb:46:in `boot_jets'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/cli.rb:25:in `start'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/lib/jets/cli.rb:5:in `start'
  /Users/NightSwinger/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.9.12/exe/jets:14:in `<top (required)>'
  /Users/NightSwinger/.rbenv/versions/2.5.3/bin/jets:23:in `load'
  /Users/NightSwinger/.rbenv/versions/2.5.3/bin/jets:23:in `<top (required)>'
```

## Step-by-step reproduction instructions

```
jets new demo
cd demo
bundle exec jets generate mailer UserMailer new_user
bundle exec jets console
```

**Comment by tongueroo** [comment]
Fixed in #288 Released in [v1.9.14](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)
