### ISSUE TITLE
Rspec execution broken after 2.2.3

### ISSUE THREAD

**Issue by lustercr** [tongueroo/jets#373]
## Checklist

- [x] Upgrade Jets
- [x] Reproducibility
- [x] Code sample
## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | stretch |
| Jets             | 2.2.3+  |
| Ruby             |2.5|

---

## Expected Behaviour

- Running rspec should execute the list of specs

## Current Behavior

- running specs throws an error
```
An error occurred while loading spec_helper.
Failure/Error: require "jets/spec_helpers"

NameError:
  uninitialized constant ActiveRecord::Tasks
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/jets-2.2.4/lib/jets/spec_helpers.rb:13:in `<top (required)>'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/jets-2.2.4/lib/jets/core_ext/kernel.rb:11:in `require'
# ./spec/spec_helper.rb:13:in `<top (required)>'
```

## Step-by-step reproduction instructions

First saw this ocurrency in my project after upgrading from `2.1.5` to `2.2.4`, thought it was something related with my project and followed up checking for any upgrade instructions, however decided to try with a new project

1 - new jets project `jets new .`
2 - bundle exec rspec
3 - same error on a new project

## Code Sample

no examples, brand new project created and running rspec

~~~sh
Cristophers-MacBook-Pro:dev cris$ mkdir jetsapi
Cristophers-MacBook-Pro:dev cris$ cd jetsapi/
Cristophers-MacBook-Pro:jetsapi cris$ jets new . --mode api --no-database
Creating a new Jets project called jetsapi.
       exist
      create  .env.development
      create  .env.test
      create  .env
      create  .gitignore
      create  .jetskeep
      create  .rspec
      create  Gemfile
      create  Procfile
      create  README.md
      create  Rakefile
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/models/application_item.rb
      create  config.ru
      create  config/application.rb
      create  config/dynamodb.yml
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/routes.rb
      create  db/.gitkeep
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/index.html
      create  spec/controllers/posts_controller_spec.rb
      create  spec/fixtures/payloads/posts-index.json
      create  spec/fixtures/payloads/posts-show.json
      create  spec/spec_helper.rb
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 12.3.3
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
Using minitest 5.12.0
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using zeitwerk 2.1.10
Using activesupport 6.0.0
Using builder 3.2.3
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.4
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.2.0
Using actionview 6.0.0
Using rack 2.0.7
Using rack-test 1.1.0
Using actionpack 6.0.0
Using globalid 0.4.2
Using activejob 6.0.0
Using mini_mime 1.0.2
Using mail 2.7.1
Using actionmailer 6.0.0
Using activemodel 6.0.0
Using activerecord 6.0.0
Using public_suffix 4.0.1
Using addressable 2.7.0
Using aws-eventstream 1.0.3
Using aws-partitions 1.218.0
Using aws-sigv4 1.1.0
Using jmespath 1.4.0
Using aws-sdk-core 3.68.0
Using aws-sdk-apigateway 1.35.0
Using aws-sdk-cloudformation 1.25.0
Using aws-sdk-cloudwatchlogs 1.25.0
Using aws-sdk-dynamodb 1.35.0
Using aws-sdk-kinesis 1.19.0
Using aws-sdk-kms 1.24.0
Using aws-sdk-lambda 1.30.0
Using aws-sdk-s3 1.48.0
Using aws-sdk-sns 1.19.0
Using aws-sdk-sqs 1.22.0
Using aws-sdk-ssm 1.55.0
Using bundler 2.0.2
Using byebug 11.0.1
Using regexp_parser 1.6.0
Using xpath 3.2.0
Using capybara 3.29.0
Using memoist 0.16.0
Using rainbow 3.0.0
Using cfn_camelizer 0.4.0
Using cfnresponse 0.4.0
Using diff-lcs 1.3
Using dotenv 2.7.5
Using dynomite 1.2.2
Using json 2.2.0
Using gems 1.1.1
Using hashie 3.6.0
Using jets-gems 0.2.0
Using jets-html-sanitizer 1.0.4
Using kramdown 2.1.0
Using mimemagic 0.3.3
Using method_source 0.9.2
Using thor 0.20.3
Using railties 6.0.0
Using recursive-open-struct 1.1.0
Using shotgun 0.9.2
Using text-table 1.2.4
Using jets 2.2.4
Using launchy 2.4.3
Using nio4r 2.5.2
Using puma 4.2.0
Using rspec-support 3.8.2
Using rspec-core 3.8.2
Using rspec-expectations 3.8.4
Using rspec-mocks 3.8.1
Using rspec 3.8.0
Bundle complete! 9 Gemfile dependencies, 79 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  git init from "."
Initialized empty Git repository in /Users/cris/dev/jetsapi/.git/
         run  git add . from "."
         run  git commit -m 'first commit' from "."
[master (root-commit) 3882e45] first commit
 29 files changed, 856 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 .jetskeep
 create mode 100644 .rspec
 create mode 100644 Gemfile
 create mode 100644 Gemfile.lock
 create mode 100644 Procfile
 create mode 100644 README.md
 create mode 100644 Rakefile
 create mode 100644 app/controllers/application_controller.rb
 create mode 100644 app/helpers/application_helper.rb
 create mode 100644 app/jobs/application_job.rb
 create mode 100644 app/models/application_item.rb
 create mode 100644 config.ru
 create mode 100644 config/application.rb
 create mode 100644 config/dynamodb.yml
 create mode 100644 config/environments/development.rb
 create mode 100644 config/environments/production.rb
 create mode 100644 config/environments/test.rb
 create mode 100644 config/routes.rb
 create mode 100644 db/.gitkeep
 create mode 100644 public/404.html
 create mode 100644 public/422.html
 create mode 100644 public/500.html
 create mode 100644 public/favicon.ico
 create mode 100644 public/index.html
 create mode 100644 spec/controllers/posts_controller_spec.rb
 create mode 100644 spec/fixtures/payloads/posts-index.json
 create mode 100644 spec/fixtures/payloads/posts-show.json
 create mode 100644 spec/spec_helper.rb
================================================================
Congrats 🎉 You have successfully created a Jets project.

Cd into the project directory:
  cd .

To start a server and test locally:
  jets server # localhost:8888 should have the Jets welcome page

Scaffold example:
  jets generate scaffold post title:string body:text published:boolean
  jets db:create db:migrate

To deploy to AWS Lambda, edit your .env.development.remote and add a DATABASE_URL endpoint.
Then run:

  jets deploy

Cristophers-MacBook-Pro:jetsapi cris$ bundle exec rspec

An error occurred while loading spec_helper.
Failure/Error: require "jets/spec_helpers"

NameError:
  uninitialized constant ActiveRecord::Tasks
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/jets-2.2.4/lib/jets/spec_helpers.rb:13:in `<top (required)>'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/jets-2.2.4/lib/jets/core_ext/kernel.rb:11:in `require'
# ./spec/spec_helper.rb:13:in `<top (required)>'

An error occurred while loading spec_helper.
Failure/Error: require "jets/spec_helpers"

NameError:
  uninitialized constant ActiveRecord::Tasks
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/jets-2.2.4/lib/jets/spec_helpers.rb:13:in `<top (required)>'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/jets-2.2.4/lib/jets/core_ext/kernel.rb:11:in `require'
# ./spec/spec_helper.rb:13:in `<top (required)>'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
# /Users/cris/.rvm/gems/ruby-2.5.5/gems/jets-2.2.4/lib/jets/core_ext/kernel.rb:11:in `require'
No examples found.
No examples found.


Finished in 0.00016 seconds (files took 1.59 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

Finished in 0.00016 seconds (files took 1.59 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

~~~

# Other

Updated to 2.2.2 instead and the rspec worked there, seem that this issue was introduced in 2.2.3 since i was also able to reproduce with that version as well as 2.2.4

**Comment by tongueroo** [comment]
Fixed in #374
