### ISSUE TITLE
Can't deploy: Invalid argument - setsockopt(2) (Errno::EINVAL)

### ISSUE THREAD

**Issue by celicoo** [tongueroo/jets#393]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   macOS Mojave v10.14.4      |
| Jets             |   2.3.1    |
| Ruby             |    2.5.3     |

---

## Expected Behaviour

I've tried to deploy my app using `AWS_PROFILE=writtio jets deploy`

## Current Behavior

The deploy fails:

```
Traceback (most recent call last):
        40: from /Users/celicoo/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
        39: from /Users/celicoo/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
        38: from /Users/celicoo/.rvm/gems/ruby-2.5.3/bin/jets:23:in `<main>'
        37: from /Users/celicoo/.rvm/gems/ruby-2.5.3/bin/jets:23:in `load'
        36: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/exe/jets:14:in `<top (required)>'
        35: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/cli.rb:5:in `start'
        34: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/cli.rb:28:in `start'
        33: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/commands/base.rb:27:in `perform'
        32: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/commands/base.rb:38:in `dispatch'
        31: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        30: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        29: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        28: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/commands/main.rb:21:in `deploy'
        27: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/commands/deploy.rb:33:in `run'
        26: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/commands/deploy.rb:85:in `build_code'
        25: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/commands/build.rb:27:in `build_code'
        24: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/code_builder.rb:38:in `build'
        23: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/code_builder.rb:38:in `chdir'
        22: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/code_builder.rb:41:in `block in build'
        21: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/code_builder.rb:341:in `package_ruby'
        20: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/code_builder.rb:352:in `build_lambda_layer'
        19: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/lambda_layer.rb:10:in `build'
        18: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/lambda_layer.rb:66:in `replace_compiled_gems'
        17: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-2.3.1/lib/jets/builders/gem_replacer.rb:11:in `run'
        16: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/check.rb:15:in `run!'
        15: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/check.rb:30:in `run'
        14: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/check.rb:30:in `each'
        13: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/check.rb:33:in `block in run'
        12: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/check.rb:33:in `each'
        11: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/check.rb:35:in `block (2 levels) in run'
        10: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/exist.rb:18:in `check'
         9: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/exist.rb:18:in `inject'
         8: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/exist.rb:18:in `each'
         7: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/exist.rb:19:in `block in check'
         6: from /Users/celicoo/.rvm/gems/ruby-2.5.3/gems/jets-gems-0.2.0/lib/jets/gems/exist.rb:34:in `url_exists?'
         5: from /Users/celicoo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1379:in `request_head'
         4: from /Users/celicoo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1455:in `request'
         3: from /Users/celicoo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:909:in `start'
         2: from /Users/celicoo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
         1: from /Users/celicoo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:943:in `connect'
/Users/celicoo/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:943:in `setsockopt': Invalid argument - setsockopt(2) (Errno::EINVAL)
```

## Solution Suggestion

Not sure. I've confirmed that the credentials are correct and that the user has enough permissions.

**Comment by celicoo** [comment]
I guess I should ask this question in the `http.rb` repository.

**Comment by celicoo** [comment]
Updating to Catalina fixed it.
