### ISSUE TITLE
Failure to invoke function when deploying from AWS CodeBuild

### ISSUE THREAD

**Issue by adam-harwood** [tongueroo/jets#80]
I'm trying to invoke, through the test feature on the AWS Lambda console, my simple function. If I run the `jets deploy` from my laptop (Ubuntu 18) then the function invokes fine. If I deploy via CodeBuild (using the `aws/codebuild/ruby:2.5.1` docker image) then I got the following error when I invoke it. I've tried to determine what the difference is between the 2 and can't. Do you have any insight as to what might be going wrong?

```
START RequestId: 9b7e9030-f1ce-11e8-b5b4-83337618b920 Version: $LATEST
2018-11-26T22:57:12.706Z	9b7e9030-f1ce-11e8-b5b4-83337618b920	subprocess output:
2018-11-26T22:57:12.706Z	9b7e9030-f1ce-11e8-b5b4-83337618b920	/var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find rake-12.3.1 in any of the sources (Bundler::GemNotFound)
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /var/task/bundled/rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'

END RequestId: 9b7e9030-f1ce-11e8-b5b4-83337618b920
REPORT RequestId: 9b7e9030-f1ce-11e8-b5b4-83337618b920	Duration: 120019.06 ms	Billed Duration: 120000 ms 	Memory Size: 1024 MB	Max Memory Used: 51 MB	
2018-11-26T22:59:11.688Z 9b7e9030-f1ce-11e8-b5b4-83337618b920 Task timed out after 120.02 seconds
```

I've paired my Gemfile down to be as simple as possible:
```
source "https://rubygems.org"

gem 'jets', '~> 1.1', '>= 1.1.3'

gem 'httparty'


group :development, :test do
    gem 'shotgun'
    gem 'rack'
end

group :test do
    gem 'rspec' # rspec test group only or we get the "irb: warn: can't alias context from irb_context warning" when starting jets console
    gem 'webmock'
end
```

And my CodeBuild spec is also really simple:
```
version: 0.2

phases:
  install:
    commands:

    - bundle install

  build:
    commands:
    - JETS_ENV=production jets deploy production
```

**Comment by adam-harwood** [comment]
I've noticed that the error message shows rbenv is using 2.5.0, instead of 2.5.1, but that seems consistent with my laptop

**Comment by adam-harwood** [comment]
Comparing at the zips deployed to Lambda, the difference is that the one built on CodeBuild has no `bundled/gems` folder, where as the local one does. `bundled/gems` obviously contains rake.

**Comment by adam-harwood** [comment]
I'm seeing this message when running on CodeBuild, that I don't see locally:
```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and 
installing your bundle as root will break this application for all non-root 
users on this machine. 
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`. 
```
Going to try changing my `jets deploy` command to be in the context of a `bundle exec`.

**Comment by adam-harwood** [comment]
Haven't been able to make any further progress on this. Hoping someone can point me in the right direction.

**Comment by adam-harwood** [comment]
After some more debugging, I'm fairly sure I've tracked down the root problem (though I don't fully understand it). The deploy command runs this to create the cache of bundled gems:
```
cd {CACHE_DIR} && env BUNDLE_IGNORE_CONFIG=1 bundle install --path bundled/gems --without development test
```
When running locally that behaves as expected, but when running on CodeBuild `--path bundled/gems` actually resolves to the directory the command is executing from, and not the one being `cd`ed into. I think the fix here is to fully specify the path to `bundled/gems` rather than rely on a relative path. I'll open a PR.

**Comment by adam-harwood** [comment]
No problem, thanks for the quick release. I've confirmed everything now builds in CodeBuild as expected.

**Comment by dakoller** [comment]
...still seeing this issue `... 

```version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
      nodejs: 10
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
      - aws s3 sync --delete _site/ s3://dakoller.net
      - aws cloudfront create-invalidation --distribution-id EOHL4V3WCMR77 --paths '/*'```
